services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud_db
      POSTGRES_USER: nextcloud_user
      POSTGRES_PASSWORD: 1234
    networks:
      - nextcloud_network

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass 1234
    volumes:
      - redis_data:/data
    networks:
      - nextcloud_network

  nextcloud:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    volumes:
      - nextcloud_data:/var/www/html
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
      - nextcloud_files:/var/www/html/data
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud_db
      POSTGRES_USER: nextcloud_user
      POSTGRES_PASSWORD: 1234
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: 1234
      NEXTCLOUD_TRUSTED_DOMAINS: localhost
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: localhost
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network
      - proxy

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
      - nextcloud_network

volumes:
  db_data:
  redis_data:
  nextcloud_data:
  nextcloud_apps:
  nextcloud_config:
  nextcloud_files:

networks:
  nextcloud_network:
    driver: bridge
  proxy:
    driver: bridge
