services:
  php-apache:
    build: .
    container_name: erms_app
    ports:
      - "${port}:80"
    depends_on:
      - mariadb
    # environment:
    #   DB_HOST: ${hostname}
    #   DB_NAME: ${db_name}
    #   DB_USER: ${db_user}
    #   DB_PASS: ${db_password}
    volumes:
      - .:/var/www/html
    networks:
      - my-network-erms

  mariadb: # service name will be a hostname.
    image: mariadb:lts
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password}
      MYSQL_DATABASE: ${db_name}
      MYSQL_USER: ${db_name}
      MYSQL_PASSWORD: ${db_password}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./erms.sql:/docker-entrypoint-initdb.d/erms.sql
    networks:
      - my-network-erms

volumes:
  mariadb_data:

networks:
  my-network-erms:
    external: true
