---
- name: Install zabbix agent on DEBIAN
  hosts: all
  become: true
  vars:
    zabbix_agent_server: []
    zabbix_agent_serveractive: "45.115.217.242" 
    zabbix_agent_hostname: "test"
    zabbix_agent_startagents: 0
    zabbix_agent_timeout: 30
    zabbix_repo_package: true
    # zabbix_agent_listeners: []
    # zabbix_agent_listeners_tls: []
  roles:
    - role: community.zabbix.zabbix_agent
