[mycloud]
202.51.75.169 ansible_user=root ansible_port=11 ansible_ssh_private_key_file=~/.ssh/dh/mycloud
# 202.51.95.103 ansible_user=dol ansible_port=22 ansible_ssh_private_key_file=~/.ssh/dh/verge
# 103.90.85.142 ansible_user=cloud ansible_port=22 ansible_python_interpreter=/usr/bin/python
# 202.51.74.193 ansible_user=root ansible_port=22 ansible_ssh_private_key_file=~/.ssh/dh/mycloud
# 202.51.70.134 ansible_user=ubuntu ansible_port=22 
# 202.51.70.56 ansible_user=ubuntu

[all]
103.90.84.225 ansible_user=root
