---
- name: Docker setup
  hosts: all
  become: true
  tasks:
    - name: Ensure docker install
      apt:
        name: docker
        state: present
    
    - name: Ensure docker is running
      service:
        name: docker
        state: started
        enabled: yes

# - name: Run shell command
#   hosts: local
#   tasks:
#     - name: ehco
#       shell: "rm /home/lun/echo.txt"
