[debian]
22.51.74.27 ansible_user=root ansible_port=22 ansible_ssh_private_key_file=~/.ssh/dh/verge
[rhel]
22.51.74.118 ansible_user=root ansible_port=22 ansible_ssh_private_key_file=~/.ssh/dh/mycloud
