# playbook
---
# play
- name: Update webservers
  hosts: all
  become: true
  # tasks
  tasks:
    - name: Ensure nodejs install
      # this is module
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Ensure nginx is install
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: no
# - name: Update db servers
#   hosts: databases
#   remote_user: root
#
#   tasks:
#     - name: Ensure postgresql is at the latest version
#       ansible.builtin.yum:
#         name: postgresql
#         state: latest
#
#     - name: Ensure that postgresql is started
#       ansible.builtin.service:
#         name: postgresql
#         state: started
